In [3]:
print("Hello World")

Hello World


In [4]:
import numpy as np

In [5]:
a = np.array([[1,2,4], [5,8,7]])
a

array([[1, 2, 4],
       [5, 8, 7]])

In [6]:
#zeros
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
#full
c = np.full((3,3),6)
c

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [8]:
#random
d = np.random.random((2,2))
d

array([[0.29252254, 0.82607314],
       [0.51963619, 0.75256542]])

In [10]:
#range
e = np.arange(0,30,5)
e

array([ 0,  5, 10, 15, 20, 25])

In [12]:
#reshape
arr = np.array([[1,2,3,4], [5,2,4,2], [1,2,0,1]])
newarr = arr.reshape(4,3)
arr, newarr

(array([[1, 2, 3, 4],
        [5, 2, 4, 2],
        [1, 2, 0, 1]]),
 array([[1, 2, 3],
        [4, 5, 2],
        [4, 2, 1],
        [2, 0, 1]]))

In [14]:
#flatten
flarr = arr.flatten()
flarr

array([1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1])

In [15]:
#ndim
arr.ndim

2

In [16]:
#shape
arr.shape

(3, 4)

In [17]:
#size
arr.size

12

In [18]:
#dtype
arr.dtype

dtype('int64')

In [19]:
#typecasting
newtype = arr.astype('i')
newtype

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]], dtype=int32)