In [7]:
''' Numpy Week 2'''

' Numpy Week 2'

In [8]:
import numpy as np

In [18]:
arr = np.array([[-1,2,0,4], [4,-0.5,6,0], [2.6,0,7,8], [3,-7,4,2.0]])
print(arr)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [19]:
#slicing
print(arr[0:3:2])
print(arr[:2,:3])

[[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]
[[-1.   2.   0. ]
 [ 4.  -0.5  6. ]]


In [22]:
#integer 
temp = arr[[0,1,2,3], [3,2,1,0]]
print(temp)

[4. 6. 0. 3.]


In [20]:
#boolean array indexing
cond = arr > 2
print(cond)

[[False False False  True]
 [ True False  True False]
 [ True False  True  True]
 [ True False  True False]]


In [21]:
#return every other element
print(arr[::2])

[[-1.   2.   0.   4. ]
 [ 2.6  0.   7.   8. ]]


In [23]:
#joining two arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr1, arr2)
arr

[1 2 3] [4 5 6]


array([1, 2, 3, 4, 5, 6])

In [24]:
#horizontal join
arr = np.hstack((arr1,arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [25]:
#vertical join
arr = np.vstack((arr1, arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#depth join
arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [27]:
#splitting array
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
