In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
b=np.array([7,8,9,10])
print(a.dot(b))

90


In [3]:
print(np.where(a%2==0))

(array([1, 3], dtype=int64),)


In [5]:
print(np.where(a<4))

(array([0, 1, 2], dtype=int64),)


In [7]:
def gll(e,f):
    if e>f:
        return e*f
    else:
        return e+f
x=[1,4,7,9]
y=[3,23,5,17]
vec=np.vectorize(gll)
print(vec(x,y))

[ 4 27 35 26]


In [8]:
# Basics of pandas --------------------------------------------------
import pandas as pd

In [12]:
#Empty dataframe
d=pd.DataFrame()
print(d)

Empty DataFrame
Columns: []
Index: []


In [17]:
Fruits=pd.Series(['Avocado','Blueberry','Melon','Orange','Kiwi'])
Cost=pd.Series([250,217,120,75,156])
frame={'Fruits':Fruits,'Cost':Cost}
result=pd.DataFrame(frame)
print(result)

      Fruits  Cost
0    Avocado   250
1  Blueberry   217
2      Melon   120
3     Orange    75
4       Kiwi   156


In [18]:
result['stock']=pd.Series([11,24,8,56,27])
print(result)

      Fruits  Cost  stock
0    Avocado   250     11
1  Blueberry   217     24
2      Melon   120      8
3     Orange    75     56
4       Kiwi   156     27


In [20]:
print(result.loc[3])

Fruits    Orange
Cost          75
stock         56
Name: 3, dtype: object


In [21]:
del result['stock']
print(result)

      Fruits  Cost
0    Avocado   250
1  Blueberry   217
2      Melon   120
3     Orange    75
4       Kiwi   156
