In [1]:
import numpy as np

In [4]:
#indexes where the values are even
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
arr, x

(array([1, 2, 3, 4, 5, 4, 4]), (array([3, 5, 6]),))

In [5]:
#indexes where values are even
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2==0)
arr, x

(array([1, 2, 3, 4, 5, 6, 7, 8]), (array([1, 3, 5, 7]),))

In [6]:
#indexes where the value 3 should be inserted
x = np.searchsorted(arr, 3, side='left')
x

np.int64(2)

In [8]:
#sorting
arr = np.array([3,2,0,1])
arr, np.sort(arr)

(array([3, 2, 0, 1]), array([0, 1, 2, 3]))

In [9]:
arr = np.array([[3,2,4], [5,0,1]])
arr, np.sort(arr)

(array([[3, 2, 4],
        [5, 0, 1]]),
 array([[2, 3, 4],
        [0, 1, 5]]))

In [10]:
#filter
arr = np.array([41,42,43,44])
x = [True, False, True, False]
newarr = arr[x]
arr, x, newarr

(array([41, 42, 43, 44]), [True, False, True, False], array([41, 43]))

In [11]:
arr = np.array([41,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
arr, filter_arr, newarr

(array([41, 42, 43, 44]), array([False, False,  True,  True]), array([43, 44]))