In [1]:
import numpy as np

In [2]:
arr1 = [10,20,30,40,50]
arr2 = [2,4,5,8,10]
a = np.array(arr1)
b = np.array(arr2)

In [3]:
a,b

(array([10, 20, 30, 40, 50]), array([ 2,  4,  5,  8, 10]))

In [4]:
a+b

array([12, 24, 35, 48, 60])

In [5]:
a-b

array([ 8, 16, 25, 32, 40])

In [6]:
a*b

array([ 20,  80, 150, 320, 500])

In [7]:
a/b

array([5., 5., 6., 5., 5.])

In [8]:
a.dot(b)

np.int64(1070)

In [9]:
scl = 5
a, a*scl

(array([10, 20, 30, 40, 50]), array([ 50, 100, 150, 200, 250]))

In [10]:
#vectorize
def customfunc(x,y):
    #return x-y if x>y, otherwise return x+y
    if x > y:
        return x-y
    else:
        return x+y
arr1 = [10,4,20]
arr2 = [2,3,20]
vec_func = np.vectorize(customfunc)
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Result: ", vec_func(arr1, arr2))

Array 1: [10, 4, 20]
Array 2: [2, 3, 20]
Result:  [ 8  1 40]
